In [ ]:
import numpy as np

In [ ]:
%%html
<style>
.pquote {
  text-align: left;
  margin: 40px 0 40px auto;
  width: 70%;
  font-size: 1.5em;
  font-style: italic;
  display: block;
  line-height: 1.3em;
  color: #5a75a7;
  font-weight: 600;
  border-left: 5px solid rgba(90, 117, 167, .1);
  padding-left: 6px;
}
.notes {
  font-style: italic;
  display: block;
  margin: 40px 10%;
}
img + em {
  text-align: center;
  display: block;
  color: gray;
  font-size: 0.9em;
  font-weight: 600;
}
</style>

$$
\newcommand\bs[1]{\boldsymbol{#1}}
$$

# 2.1 Scalaires, vecteurs, matrices et tenseurs


Commençons par quelques définitions de base :

<img src="images/scalar-vector-matrix-tensor.png" width="400" alt="Exemple d'un scalaire, d'un vecteur, d'une matrice et d'un tenseur." title=Différence entre un scalaire, un vecteur, une matrice et un tenseur">
<em>Différence entre un scalaire, un vecteur, une matrice et un tenseur</em>

- Un scalaire est un nombre unique
- Un vecteur est un tableau de nombres.

$$
\bs{x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

- Une matrice est un tableau à deux dimensions

$$
\bs{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

- Un tenseur est un tableau à $n$-dimension avec $n>2$

### Exemple 1.

#### Créer un vecteur avec Python et Numpy

*Astuce de codage* : Contrairement à la fonction `matrix()` qui crée nécessairement des matrices à $2$ dimension, vous pouvez créer des tableaux à $n$ dimension avec la fonction `array()`. Le principal avantage d'utiliser `matrix()` est de disposer de méthodes utiles (transposition conjuguée, inverse, opérations matricielles...). Nous allons utiliser la fonction `array()` dans cette série.

Nous allons commencer par créer un vecteur. Il s'agit simplement d'un tableau à $1$ dimension :

In [ ]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

### Exemple 2.

#### Créer une matrice (3x2) avec des parenthèses imbriquées

La fonction `array()` peut également créer des tableaux à $2$ dimensions avec des parenthèses imbriquées :

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### Forme

La forme d'un tableau (c'est-à-dire ses dimensions) vous indique le nombre de valeurs pour chaque dimension. Pour un tableau à $2$ de dimensions, elle vous donnera le nombre de lignes et le nombre de colonnes. Trouvons la forme de notre tableau précédent de $2$-dimensions `A`. Puisque `A` est un tableau Numpy (il a été créé avec la fonction `array()`), vous pouvez accéder à sa forme avec :

In [ ]:
A.shape

(3, 2)

Nous pouvons voir que $\bs{A}$ a 3 lignes et 2 colonnes.

Vérifions la forme de notre premier vecteur :

In [ ]:
x.shape

(4,)

Comme prévu, vous pouvez voir que $\bs{x}$ n'a qu'une seule dimension. Le nombre correspond à la longueur du tableau :

In [ ]:
len(x)

4

# Transposition

La transposition permet de convertir un vecteur ligne en vecteur colonne et vice versa :

<img src="images/vector-transposition.png" alt="Transposition d'un vecteur" title="Vecteur transposition" width="200">
<em>Vecteur transposition</em>

La transposée $\bs{A}^{\text{T}}$ de la matrice $\bs{A}$ correspond aux axes inversés. Si la matrice est une matrice carrée (même nombre de colonnes et de lignes) :

<img src="images/square-matrix-transposition.png" 
alt="Transposition d'une matrice carrée" title="Transposition de la matrice carrée" width="300">
<em>transposition de matrice carrée</em>

Si la matrice n'est pas carrée, l'idée est la même.:

<img src="images/non-squared-matrix-transposition.png" 
alt="Transposition d'une matrice carrée" title="Transposition de matrice non carrée" width="300">
<emTransposition de matrice non carrée</em>


L'exposant $^\text{T}$ est utilisé pour les matrices transposées.
$$
\bs{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$$

$$
\bs{A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}
$$

La forme ($m \times n$) est inversée et devient ($n \times m$).

<img src="images/dimensions-transposition-matrix.png" alt="Dimensions de la transposition de la matrice" title="Dimensions de la transposition de la matrice" width="300">
<em>Dimensions de la transposition de la matrice</em>

### Exemple 3.

#### Créez une matrice A et transposez-la

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

Nous pouvons vérifier les dimensions des matrices :

In [ ]:
A.shape

(3, 2)

In [ ]:
A_t.shape

(2, 3)

On peut voir que le nombre de colonnes devient le nombre de lignes avec la transposition et vice versa.

# Addition

<img src="images/matrix-addition.png" alt="Addition de deux matrices" title="Addition de deux matrices" width="300">
<em>Addition de deux matrices</em>

Les matrices peuvent être additionnées si elles ont la même forme :

$$\bs{A} + \bs{B} = \bs{C}$$

Chaque cellule de $\bs{A}$ est ajoutée à la cellule correspondante de $\bs{B}$ :
$$\bs{A}_{i,j} + \bs{B}_{i,j} = \bs{C}_{i,j}$$

$i$ est l'indice de ligne et $j$ l'indice de colonne.

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$$

Les formes de $\bs{A}$, $\bs{B}$ et $\bs{C}$ sont identiques. Vérifions-le dans un exemple :

### Exemple 4.

#### Créer deux matrices A et B et les additionner

Avec Numpy, vous pouvez ajouter des matrices comme vous le feriez pour des vecteurs ou des scalaires.

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [ ]:
# Add matrices A and B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

Il est également possible d'ajouter un scalaire à une matrice. Cela signifie ajouter ce scalaire à chaque cellule de la matrice.

$$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$$

### Exemple 5.

#### Ajouter un scalaire à une matrice

In [ ]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Exemple: Ajouter 4 à la matrice A
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Diffusion

Numpy peut gérer des opérations sur des tableaux de formes différentes. Le plus petit tableau sera étendu pour correspondre à la forme du plus grand. L'avantage est que cela est fait en `C` sous le capot (comme toute opération vectorielle dans Numpy). En fait, nous avons utilisé la diffusion dans l'exemple 5. Le scalaire a été converti en un tableau de même forme que $\bs{A}$.

Voici un autre exemple générique :


$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}
$$

est equivalent à

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$

où la matrice ($3 \times 1$) est convertie à la bonne forme ($3 \times 2$) en copiant la première colonne. Numpy le fera automatiquement si les formes peuvent correspondre.

### Exemple 6.

#### Additionner deux matrices de formes différentes

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B = np.array([[2], [4], [6]])
B

array([[2],
       [4],
       [6]])

In [ ]:
# Broadcasting
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])